// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *About page → Statement Section*
 */
export interface AboutPageDocumentDataStatementSectionItem {
  /**
   * Title field in *About page → Statement Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Mission Statement / Vision Statement
   * - **API ID Path**: about_page.statement_section[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *About page → Statement Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: We envision 4herfrika in all tertiary institutions...
   * - **API ID Path**: about_page.statement_section[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Image field in *About page → Statement Section*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.statement_section[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Position field in *About page → Statement Section*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.statement_section[].image_position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  image_position: prismic.SelectField<"Left" | "Right">;
}

/**
 * Item in *About page → Frequently Asked Questions*
 */
export interface AboutPageDocumentDataFrequentlyAskedQuestionsItem {
  /**
   * Question field in *About page → Frequently Asked Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.frequently_asked_questions[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *About page → Frequently Asked Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.frequently_asked_questions[].answer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  answer: prismic.KeyTextField;
}

type AboutPageDocumentDataSlicesSlice = never;

/**
 * Content for About page documents
 */
interface AboutPageDocumentData {
  /**
   * Hero Image field in *About page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Statement Section field in *About page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.statement_section[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  statement_section: prismic.GroupField<
    Simplify<AboutPageDocumentDataStatementSectionItem>
  >;

  /**
   * Frequently Asked Questions field in *About page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.frequently_asked_questions[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  frequently_asked_questions: prismic.GroupField<
    Simplify<AboutPageDocumentDataFrequentlyAskedQuestionsItem>
  >;

  /**
   * Slice Zone field in *About page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AboutPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *About page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About page document from Prismic
 *
 * - **API ID**: `about_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutPageDocumentData>,
    "about_page",
    Lang
  >;

/**
 * Content for Blog Category documents
 */
interface BlogCategoryDocumentData {
  /**
   * Name field in *Blog Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_category.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;
}

/**
 * Blog Category document from Prismic
 *
 * - **API ID**: `blog_category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogCategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogCategoryDocumentData>,
    "blog_category",
    Lang
  >;

type BlogPostDocumentDataSlicesSlice = BlogContentSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Category field in *Blog Post*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  category: ContentRelationshipFieldWithData<
    [{ id: "blog_category"; fields: ["name"] }]
  >;

  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Author field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField;

  /**
   * Cover Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.cover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Was Submitted On Website field in *Blog Post*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blog_post.submitted_story
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  submitted_story: prismic.BooleanField;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice>;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

/**
 * Item in *Frequently Asked Question Section (About Page) → FAQ*
 */
export interface FaqDocumentDataFaqItem {
  /**
   * Question field in *Frequently Asked Question Section (About Page) → FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.faq[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *Frequently Asked Question Section (About Page) → FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.faq[].answer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  answer: prismic.KeyTextField;
}

/**
 * Content for Frequently Asked Question Section (About Page) documents
 */
interface FaqDocumentData {
  /**
   * Title field in *Frequently Asked Question Section (About Page)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * FAQ field in *Frequently Asked Question Section (About Page)*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.faq[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faq: prismic.GroupField<Simplify<FaqDocumentDataFaqItem>>;
}

/**
 * Frequently Asked Question Section (About Page) document from Prismic
 *
 * - **API ID**: `faq`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FaqDocumentData>, "faq", Lang>;

/**
 * Item in *FAQ Page → Frequently Asked Questions*
 */
export interface FaqPageDocumentDataFrequentlyAskedQuestionsItem {
  /**
   * FAQ Section field in *FAQ Page → Frequently Asked Questions*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_page.frequently_asked_questions[].section
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  section: prismic.ContentRelationshipField<"faq">;
}

type FaqPageDocumentDataSlicesSlice = never;

/**
 * Content for FAQ Page documents
 */
interface FaqPageDocumentData {
  /**
   * Header IMage field in *FAQ Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_page.header_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  header_image: prismic.ImageField<never>;

  /**
   * Frequently Asked Questions field in *FAQ Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_page.frequently_asked_questions[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  frequently_asked_questions: prismic.GroupField<
    Simplify<FaqPageDocumentDataFrequentlyAskedQuestionsItem>
  >;

  /**
   * Slice Zone field in *FAQ Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<FaqPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *FAQ Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: faq_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *FAQ Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: faq_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *FAQ Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * FAQ Page document from Prismic
 *
 * - **API ID**: `faq_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FaqPageDocumentData>,
    "faq_page",
    Lang
  >;

/**
 * Item in *Homepage → Testimonials*
 */
export interface HomepageDocumentDataTestimonialsItem {
  /**
   * Profile Picture field in *Homepage → Testimonials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.testimonials[].profile_picture
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  profile_picture: prismic.ImageField<never>;

  /**
   * Testimonial field in *Homepage → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.testimonials[].testimonial
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  testimonial: prismic.KeyTextField;

  /**
   * Name field in *Homepage → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.testimonials[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Role and Location field in *Homepage → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Founder, ReadEvolve
   * - **API ID Path**: homepage.testimonials[].role_and_location
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role_and_location: prismic.KeyTextField;

  /**
   * Rating field in *Homepage → Testimonials*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.testimonials[].rating
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  rating: prismic.SelectField<"1" | "2" | "3" | "4" | "5">;
}

type HomepageDocumentDataSlicesSlice = never;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Hero Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Testimonials field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.testimonials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  testimonials: prismic.GroupField<
    Simplify<HomepageDocumentDataTestimonialsItem>
  >;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>; /**
   * Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.ambassador_description
   * - **Tab**: Become an Ambassador
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  ambassador_description: prismic.KeyTextField;

  /**
   * Register Link field in *Homepage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.ambassador_link
   * - **Tab**: Become an Ambassador
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  ambassador_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Ambassador Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.ambassador_image
   * - **Tab**: Become an Ambassador
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  ambassador_image: prismic.ImageField<never>; /**
   * Members field in *Homepage*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.members
   * - **Tab**: Statistics
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  members: prismic.NumberField;

  /**
   * Campuses field in *Homepage*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.campuses
   * - **Tab**: Statistics
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  campuses: prismic.NumberField;

  /**
   * Countries field in *Homepage*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.countries
   * - **Tab**: Statistics
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  countries: prismic.NumberField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Mentor → Links*
 */
export interface MentorDocumentDataLinksItem {
  /**
   * Title field in *Mentor → Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: mentor.links[].title
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  title: prismic.SelectField<"LinkedIn" | "X" | "Instagram">;

  /**
   * Link field in *Mentor → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mentor.links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Mentor documents
 */
interface MentorDocumentData {
  /**
   * Image field in *Mentor*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mentor.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *Mentor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mentor.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Role field in *Mentor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mentor.role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * Description field in *Mentor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mentor.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Links field in *Mentor*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mentor.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links: prismic.GroupField<Simplify<MentorDocumentDataLinksItem>>;

  /**
   * Availability field in *Mentor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mentor.availability
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  availability: prismic.KeyTextField;
}

/**
 * Mentor document from Prismic
 *
 * - **API ID**: `mentor`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MentorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<MentorDocumentData>, "mentor", Lang>;

/**
 * Item in *Campus → Testimonials*
 */
export interface CampusDocumentDataTestimonialsItem {
  /**
   * Quote field in *Campus → Testimonials*
   *
   * - **Field Type**: Text
   * - **API ID Path**: campus.testimonials[].quote
   */
  quote: prismic.KeyTextField;

  /**
   * Name field in *Campus → Testimonials*
   *
   * - **Field Type**: Text
   * - **API ID Path**: campus.testimonials[].name
   */
  name: prismic.KeyTextField;

  /**
   * Role field in *Campus → Testimonials*
   *
   * - **Field Type**: Text
   * - **API ID Path**: campus.testimonials[].role
   */
  role: prismic.KeyTextField;

  /**
   * Photo field in *Campus → Testimonials*
   *
   * - **Field Type**: Image
   * - **API ID Path**: campus.testimonials[].photo
   */
  photo: prismic.ImageField<never>;
}

/**
 * Item in *Campus → Upcoming Events*
 */
export interface CampusDocumentDataEventsItem {
  /**
   * Date field in *Campus → Upcoming Events*
   *
   * - **Field Type**: Date
   * - **API ID Path**: campus.events[].date
   */
  date: prismic.DateField;

  /**
   * Title field in *Campus → Upcoming Events*
   *
   * - **Field Type**: Text
   * - **API ID Path**: campus.events[].title
   */
  title: prismic.KeyTextField;

  /**
   * Location field in *Campus → Upcoming Events*
   *
   * - **Field Type**: Text
   * - **API ID Path**: campus.events[].location
   */
  location: prismic.KeyTextField;

  /**
   * Link field in *Campus → Upcoming Events*
   *
   * - **Field Type**: Link
   * - **API ID Path**: campus.events[].link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Campus → Lead Ambassador Socials*
 */
export interface CampusDocumentDataLeadAmbassadorSocialsItem {
  /**
   * Platform field in *Campus → Lead Ambassador Socials*
   *
   * - **Field Type**: Select
   * - **API ID Path**: campus.lead_ambassador_socials[].platform
   */
  platform: prismic.SelectField<"LinkedIn" | "X" | "Instagram">;

  /**
   * URL field in *Campus → Lead Ambassador Socials*
   *
   * - **Field Type**: Link
   * - **API ID Path**: campus.lead_ambassador_socials[].url
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Campus → Milestones*
 */
export interface CampusDocumentDataMilestonesItem {
  /**
   * Date field in *Campus → Milestones*
   *
   * - **Field Type**: Date
   * - **API ID Path**: campus.milestones[].date
   */
  date: prismic.DateField;

  /**
   * Title field in *Campus → Milestones*
   *
   * - **Field Type**: Text
   * - **API ID Path**: campus.milestones[].title
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Campus → Milestones*
   *
   * - **Field Type**: Text
   * - **API ID Path**: campus.milestones[].description
   */
  description: prismic.KeyTextField;
}

/**
 * Item in *Campus → Programs*
 */
export interface CampusDocumentDataProgramsItem {
  /**
   * Name field in *Campus → Programs*
   *
   * - **Field Type**: Text
   * - **API ID Path**: campus.programs[].name
   */
  name: prismic.KeyTextField;

  /**
   * Description field in *Campus → Programs*
   *
   * - **Field Type**: Text
   * - **API ID Path**: campus.programs[].description
   */
  description: prismic.KeyTextField;
}

/**
 * Item in *Campus → Gallery*
 */
export interface CampusDocumentDataGalleryItem {
  /**
   * Image field in *Campus → Gallery*
   *
   * - **Field Type**: Image
   * - **API ID Path**: campus.gallery[].image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *Campus → Gallery*
   *
   * - **Field Type**: Text
   * - **API ID Path**: campus.gallery[].caption
   */
  caption: prismic.KeyTextField;
}

/**
 * Content for Campus documents
 */
interface CampusDocumentData {
  /**
   * Name field in *Campus*
   *
   * - **API ID Path**: campus.name
   */
  name: prismic.KeyTextField;

  /**
   * University field in *Campus*
   *
   * - **API ID Path**: campus.university
   */
  university: prismic.KeyTextField;

  /**
   * Country field in *Campus*
   *
   * - **API ID Path**: campus.country
   */
  country: prismic.KeyTextField;

  /**
   * Summary field in *Campus*
   *
   * - **API ID Path**: campus.summary
   */
  summary: prismic.KeyTextField;

  /**
   * Cover Image field in *Campus*
   *
   * - **API ID Path**: campus.cover_image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Lead Ambassador field in *Campus*
   *
   * - **API ID Path**: campus.lead_ambassador
   */
  lead_ambassador: prismic.KeyTextField;

  /**
   * Lead Ambassador Role field in *Campus*
   *
   * - **API ID Path**: campus.lead_ambassador_role
   */
  lead_ambassador_role: prismic.KeyTextField;

  /**
   * Lead Ambassador Photo field in *Campus*
   *
   * - **API ID Path**: campus.lead_ambassador_photo
   */
  lead_ambassador_photo: prismic.ImageField<never>;

  /**
   * Lead Ambassador Bio field in *Campus*
   *
   * - **API ID Path**: campus.lead_ambassador_bio
   */
  lead_ambassador_bio: prismic.KeyTextField;

  /**
   * Lead Ambassador Socials field in *Campus*
   *
   * - **API ID Path**: campus.lead_ambassador_socials[]
   */
  lead_ambassador_socials: prismic.GroupField<
    Simplify<CampusDocumentDataLeadAmbassadorSocialsItem>
  >;

  /**
   * Founded Date field in *Campus*
   *
   * - **API ID Path**: campus.founded_date
   */
  founded_date: prismic.DateField;

  /**
   * Member Count field in *Campus*
   *
   * - **API ID Path**: campus.member_count
   */
  member_count: prismic.NumberField;

  /**
   * Body field in *Campus*
   *
   * - **API ID Path**: campus.body
   */
  body: prismic.RichTextField;

  /**
   * Milestones field in *Campus*
   *
   * - **API ID Path**: campus.milestones[]
   */
  milestones: prismic.GroupField<Simplify<CampusDocumentDataMilestonesItem>>;

  /**
   * Upcoming Events field in *Campus*
   *
   * - **API ID Path**: campus.events[]
   */
  events: prismic.GroupField<Simplify<CampusDocumentDataEventsItem>>;

  /**
   * Testimonials field in *Campus*
   *
   * - **API ID Path**: campus.testimonials[]
   */
  testimonials: prismic.GroupField<
    Simplify<CampusDocumentDataTestimonialsItem>
  >;

  /**
   * Programs field in *Campus*
   *
   * - **API ID Path**: campus.programs[]
   */
  programs: prismic.GroupField<Simplify<CampusDocumentDataProgramsItem>>;

  /**
   * Gallery field in *Campus*
   *
   * - **API ID Path**: campus.gallery[]
   */
  gallery: prismic.GroupField<Simplify<CampusDocumentDataGalleryItem>>;
}

/**
 * Campus document from Prismic
 *
 * - **API ID**: `campus`
 * - **Repeatable**: `true`
 */
export type CampusDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<CampusDocumentData>, "campus", Lang>;

export type AllDocumentTypes =
  | AboutPageDocument
  | BlogCategoryDocument
  | BlogPostDocument
  | CampusDocument
  | FaqDocument
  | FaqPageDocument
  | HomepageDocument
  | MentorDocument;

/**
 * Primary content in *BlogContent → Paragraph → Primary*
 */
export interface BlogContentSliceDefaultPrimary {
  /**
   * Text field in *BlogContent → Paragraph → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_content.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Paragraph variation for BlogContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogContentSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *BlogContent → Quote → Primary*
 */
export interface BlogContentSliceQuotePrimary {
  /**
   * Text field in *BlogContent → Quote → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_content.quote.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;
}

/**
 * Quote variation for BlogContent Slice
 *
 * - **API ID**: `quote`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogContentSliceQuote = prismic.SharedSliceVariation<
  "quote",
  Simplify<BlogContentSliceQuotePrimary>,
  never
>;

/**
 * Slice variation for *BlogContent*
 */
type BlogContentSliceVariation =
  | BlogContentSliceDefault
  | BlogContentSliceQuote;

/**
 * BlogContent Shared Slice
 *
 * - **API ID**: `blog_content`
 * - **Description**: BlogContent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogContentSlice = prismic.SharedSlice<
  "blog_content",
  BlogContentSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutPageDocument,
      AboutPageDocumentData,
      AboutPageDocumentDataStatementSectionItem,
      AboutPageDocumentDataFrequentlyAskedQuestionsItem,
      AboutPageDocumentDataSlicesSlice,
      BlogCategoryDocument,
      BlogCategoryDocumentData,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      CampusDocument,
      CampusDocumentData,
      CampusDocumentDataEventsItem,
      CampusDocumentDataGalleryItem,
      CampusDocumentDataLeadAmbassadorSocialsItem,
      CampusDocumentDataMilestonesItem,
      CampusDocumentDataProgramsItem,
      CampusDocumentDataTestimonialsItem,
      FaqDocument,
      FaqDocumentData,
      FaqDocumentDataFaqItem,
      FaqPageDocument,
      FaqPageDocumentData,
      FaqPageDocumentDataFrequentlyAskedQuestionsItem,
      FaqPageDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataTestimonialsItem,
      HomepageDocumentDataSlicesSlice,
      MentorDocument,
      MentorDocumentData,
      MentorDocumentDataLinksItem,
      AllDocumentTypes,
      BlogContentSlice,
      BlogContentSliceDefaultPrimary,
      BlogContentSliceQuotePrimary,
      BlogContentSliceVariation,
      BlogContentSliceDefault,
      BlogContentSliceQuote,
    };
  }
}
