// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Homepage → Testimonials*
 */
export interface HomepageDocumentDataTestimonialsItem {
  /**
   * Profile Picture field in *Homepage → Testimonials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.testimonials[].profile_picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_picture: prismic.ImageField<never>;

  /**
   * Testimonial field in *Homepage → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.testimonials[].testimonial
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testimonial: prismic.KeyTextField;

  /**
   * Name field in *Homepage → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.testimonials[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Role and Location field in *Homepage → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Founder, ReadEvolve
   * - **API ID Path**: homepage.testimonials[].role_and_location
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role_and_location: prismic.KeyTextField;

  /**
   * Rating field in *Homepage → Testimonials*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.testimonials[].rating
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  rating: prismic.SelectField<"1" | "2" | "3" | "4" | "5">;
}

type HomepageDocumentDataSlicesSlice = never;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Hero Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Testimonials field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.testimonials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonials: prismic.GroupField<
    Simplify<HomepageDocumentDataTestimonialsItem>
  >;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never> /**
   * Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.ambassador_description
   * - **Tab**: Become an Ambassador
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  ambassador_description: prismic.KeyTextField;

  /**
   * Register Link field in *Homepage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.ambassador_link
   * - **Tab**: Become an Ambassador
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  ambassador_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Ambassador Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.ambassador_image
   * - **Tab**: Become an Ambassador
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  ambassador_image: prismic.ImageField<never> /**
   * Members field in *Homepage*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.members
   * - **Tab**: Statistics
   * - **Documentation**: https://prismic.io/docs/field#number
   */;
  members: prismic.NumberField;

  /**
   * Campuses field in *Homepage*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.campuses
   * - **Tab**: Statistics
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  campuses: prismic.NumberField;

  /**
   * Countries field in *Homepage*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.countries
   * - **Tab**: Statistics
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  countries: prismic.NumberField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataTestimonialsItem,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
