name = "4herfrika"
compatibility_date = "2023-07-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"                          # i.e. available in your Worker on env.DB
database_name = "prisma-demo-db"
database_id = "__YOUR_D1_DATABASE_ID__"
